<!-- NIMA CHANGES - disabled this -->
<!--<div id="meee">-->
<!--    <div id="econt-iframe-modal">-->
<!--        <div id="place_iframe_here" class="content"></div>-->
<!--    </div>-->
<!--</div>-->

<?php
$ajaxurl = $block->getAjaxUrl();
$econtData = $block->getEcontData();
?>
<script type="text/x-magento-init">
    {
        "*": {
            "Oxl_Delivery/js/view/cms-block": {
                "ajaxUrl": "<?php echo $ajaxurl; ?>",
                "econtData": <?php echo json_encode($econtData); ?>
            }
        }
    }
</script>

<style>
    #place_iframe_here {
        padding-top: 25px;
    }

    #econt-iframe-modal .fieldset {
        border: 1px solid #ccc;
        padding: 10px;
        margin-top: 10px;
    }

    #econt-iframe-modal .fieldset .legend {
        margin: 0;
    }

    #place_iframe_here > iframe {
        width: 100%;
        min-height: 500px;
        border: none;
        height: 710px;
        overflow: hidden
    }

    .modal-content {
        font-size: 16px;
    }
</style>
